### ISSUE TITLE
removed and re added error

### ISSUE THREAD

**Issue by koryteg** [markwryan/hipgif#3]
![screen shot 2015-06-30 at 1 25 34 pm](https://cloud.githubusercontent.com/assets/777967/8441179/90b3a364-1f2b-11e5-8891-dd55ffa62ffa.png)

getting this error while installing the integration

**Comment by markwryan** [comment]
I'm not seeing any issues in the logs, but the plugin is hosted on Heroku, so they're limited to 1500 lines... I do see a few successful new installs of the plugin.

Are you trying to re-add the app after you had added it before?

**Comment by koryteg** [comment]
yeah, I had it added, then it stopped working for me for a bit, and then uninstalled and tried to reinstall. but hey. just tried again and it worked now. so nvm.

**Comment by markwryan** [comment]
OK great to hear! I'm going to choose to blame the Heroku instance being flaky ;)
